title: ROB 102 @ UM F24
description: University of Michigan offering of Robotics 102 in Fall 24
theme: just-the-docs

url: https://robotics102.org/um-f25
baseurl: '' # the subpath of your site, e.g. /blog

favicon_ico: "/assets/images/icon.png"

search_enabled: false

# Aux links for the upper right navigation
aux_links:
  "HelloRob": https://hellorob.org
  "PrairieLearn": https://us.prairielearn.com/
  "Autograder.io": https://autograder.io/
  "Piazza": https://piazza.com/umich/fall2025/rob102fa2025
  "Google Drive": https://drive.google.com/drive/folders/1DsZz9f_SvsMi2mMTJYCxw7rybQgjfams?usp=sharing

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Collections for website data
collections:
  staff:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staff
    values:
      layout: staff
      subpath: '/assets/images/staff/'
